In [1]:
# import resources
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import iqr
import statistics

amir_deals = pd.read_csv('amir_deals.csv')
food_consumption = pd.read_csv('food_consumption.csv')
world_happiness = pd.read_csv('world_happiness.csv')

# Sampling a dataframe

In [2]:
food_consumption.sample()

     Unnamed: 0 country food_category  consumption  co2_emission
767         768  Poland          rice         0.95          1.22

In [3]:
# Set a seeding so the operation can be repeated and still give the result
np.random.seed(999170)
food_consumption.sample()

     Unnamed: 0  country food_category  consumption  co2_emission
610         611  Romania          eggs        12.94         11.89

In [4]:
# pick mutiple elements
np.random.seed(29)
food_consumption.sample(4)

      Unnamed: 0    country food_category  consumption  co2_emission
572          573    Ecuador          pork        14.44         51.11
10            11  Argentina          nuts         0.49          0.87
697          698   Pakistan          fish         1.87          2.99
1177        1178   Ethiopia          pork         0.02          0.07

# Sampling with/without replacement

In [5]:
# with replacement: independant events
amir_deals.sample(5, replace=True)

     Unnamed: 0    product   client status   amount  num_users
114         115  Product A  Current    Won  3371.70         18
121         122  Product B  Current    Won  4831.73         12
129         130  Product B  Current    Won  6509.25         53
136         137  Product B  Current    Won  2924.29         32
61           62  Product D  Current    Won  6733.62         27

In [6]:
# without replacement
amir_deals.sample(5)

     Unnamed: 0    product   client status   amount  num_users
48           49  Product C  Current   Lost  3727.66         19
124         125  Product C  Current    Won   482.01         65
172         173  Product D  Current   Lost  3086.88         55
65           66  Product B      New   Lost  2746.79         50
139         140  Product B  Current    Won  4566.61          9

# Law of large sample

As the size of the sample increase the more the mean is closed to the expected value

# Uniform distribution in python

In [8]:
from scipy.stats import uniform

# P(waiting time >= 7) = uniform.cdf(7,0,12)
# Where 12 represent the uniform time
uniform.cdf(7,0,12)

np.float64(0.5833333333333334)

In [9]:
help(uniform.cdf)

Help on method cdf in module scipy.stats._distn_infrastructure:

cdf(x, *args, **kwds) method of scipy.stats._continuous_distns.uniform_gen instance
    Cumulative distribution function of the given RV.

    Parameters
    ----------
    x : array_like
        quantiles
    arg1, arg2, arg3,... : array_like
        The shape parameter(s) for the distribution (see docstring of the
        instance object for more information)
    loc : array_like, optional
        location parameter (default=0)
    scale : array_like, optional
        scale parameter (default=1)

    Returns
    -------
    cdf : ndarray
        Cumulative distribution function evaluated at `x`

In [10]:
# P(4 <= waiting time <= 7)= P(waiting time >= 7) - P(waiting time >=4)
uniform.cdf(7,0,12) - uniform.cdf(4,0,12)

np.float64(0.25000000000000006)