In [1]:
# import resources
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import iqr
import statistics

amir_deals = pd.read_csv('amir_deals.csv')
food_consumption = pd.read_csv('food_consumption.csv')
world_happiness = pd.read_csv('world_happiness.csv')

# Sampling a dataframe

In [5]:
food_consumption.sample()

     Unnamed: 0   country food_category  consumption  co2_emission
880         881  Slovakia          pork        31.78        112.49

In [30]:
# Set a seeding so the operation can be repeated and still give the result
np.random.seed(999170)
food_consumption.sample()

     Unnamed: 0  country food_category  consumption  co2_emission
610         611  Romania          eggs        12.94         11.89

In [31]:
# pick mutiple elements
np.random.seed(29)
food_consumption.sample(4)

      Unnamed: 0    country food_category  consumption  co2_emission
572          573    Ecuador          pork        14.44         51.11
10            11  Argentina          nuts         0.49          0.87
697          698   Pakistan          fish         1.87          2.99
1177        1178   Ethiopia          pork         0.02          0.07

# Sampling with/without replacement

In [33]:
# with replacement: independant events
amir_deals.sample(5, replace=True)

     Unnamed: 0    product   client status   amount  num_users
78           79  Product C  Current    Won  1300.89         42
11           12  Product C      New   Lost  2480.33          6
117         118  Product D  Current   Lost  3416.82         12
99          100  Product A  Current    Won  5758.67         23
43           44  Product D  Current    Won  3328.79         40

In [34]:
# without replacement
amir_deals.sample(5)

     Unnamed: 0    product   client status   amount  num_users
130         131  Product A  Current    Won  3425.45         82
106         107  Product H  Current    Won  4547.97         13
177         178  Product D      New   Lost  7320.05         72
116         117  Product B      New   Lost  5287.36         81
65           66  Product B      New   Lost  2746.79         50